using UnityEngine.SceneManagement;

namespace JotunnDoc.Docs
{
    class LanguageDoc : Doc
    {
        public LanguageDoc() : base("localization/language-list.md")
        {
            SceneManager.sceneLoaded += docLanguages;
        }

        private void docLanguages(Scene scene, LoadSceneMode mode)
        {
            if (Generated)
            {
                return;
            }

            Jotunn.Logger.LogInfo("Documenting languages");

            AddHeader(1, "Language list");
            AddText("All of the languages currently in the game.");
            AddText("This file is automatically generated from Valheim using the JotunnDoc mod found on our GitHub.");

            AddTableHeader("Folder Name", "Localized Name");

            foreach (var languageKey in Localization.instance.m_languages)
            {
                var localizedName = Localization.instance.Localize("$language_" + languageKey.ToLower());
                AddTableRow(languageKey, localizedName);
            }

            Save();
        }
    }
}
